
//// MAIN SCREEN DEFINES ////
// 80 x 80 pixels, fillRect(CONTACTS_BUTTON_X, CONTACTS_BUTTON_Y, CONTACTS_BUTTON_X_WIDTH, CONTACTS_BUTTON_Y_WIDTH)
//#define CONTACTS_SCREEN_CODE 0000000000001110
#define CONTACTS_BUTTON_X    220
#define CONTACTS_BUTTON_Y    150
#define CONTACTS_BUTTON_X_WIDTH 80
#define CONTACTS_BUTTON_Y_WIDTH 80

// 80 x 80 pixels, fillRect(LOG_BUTTON_X, LOG_BUTTON_Y, LOG_BUTTON_X_WITDTH, LOG_BUTTON_Y_WIDTH)
//#define LOG_SCREEN_CODE 0000000000000001
#define LOG_BUTTON_X    20
#define LOG_BUTTON_Y    150
#define LOG_BUTTON_X_WIDTH 80
#define LOG_BUTTON_Y_WIDTH 80
/****************************/


//// CONTACTS SCREEEN DEFINES ////
// 80 x 80 pixels
//#define MAIN_SCREEN_CODE 0000000000000010
#define MAIN_BUTTON_X   0
#define MAIN_BUTTON_Y   0
#define MAIN_BUTTON_X_WIDTH 80
#define MAIN_BUTTON_Y_WIDTH 80

// 80 x 80 pixels
//#define ADD_CONTACT_SCREEN_CODE 0000000000000110
#define ADD_CONTACT_BUTTON_X    140
#define ADD_CONTACT_BUTTON_Y    0
#define ADD_CONTACT_BUTTON_X_WIDTH 80
#define ADD_CONTACT_BUTTON_Y_WIDTH 80

// 80 x 80 pixels
//#define DELETE_CONTACT_SCREEN_CODE  0000000000000111
#define DELETE_CONTACT_BUTTON_X 240
#define DELETE_CONTACT_BUTTON_Y 0
#define DELETE_CONTACT_BUTTON_X_WIDTH 80
#define DELETE_CONTACT_BUTTON_Y_WIDTH 80

// 40 x 80 pixels
//#define CONTACTS_PG_DOWN_SCREEN_CODE   0000000000001000
#define CONTACTS_PG_DOWN_BUTTON_X   280
#define CONTACTS_PG_DOWN_BUTTON_Y   100
#define CONTACTS_PG_DOWN_BUTTON_X_WIDTH 40
#define CONTACTS_PG_DOWN_BUTTON_Y_WIDTH 80

// 40 x 80 pixels
#define CONTACTS_PG_UP_SCREEN_CODE  0000000000001001
#define CONTACTS_PG_UP_BUTTON_X 280
#define CONTACTS_PG_UP_BUTTON_Y 90
#define CONTACTS_PG_UP_BUTTON_X_WIDTH 40
#define CONTACTS_PG_UP_BUTTON_Y_WIDTH 80

// Contact list 1-4 are 260 x 37
//#define CONTACT1_SCREEN_CODE    0000000000001010
#define CONTACT1_BUTTON_X   0
#define CONTACT1_BUTTON_Y   90
#define CONTACT1_BUTTON_X_WIDTH 260
#define CONTACT1_BUTTON_Y_WIDTH 37

//#define CONTACT2_SCREEN_CODE    0000000000001011
#define CONTACT2_BUTTON_X 0
#define CONTACT2_BUTTON_Y 127 
#define CONTACT2_BUTTON_X_WIDTH 260
#define CONTACT2_BUTTON_Y_WIDTH 37


//#define CONTACT3_SCREEN_CODE    0000000000001100
#define CONTACT3_BUTTON_X 0
#define CONTACT3_BUTTON_Y 164
#define CONTACT3_BUTTON_X_WIDTH 260
#define CONTACT3_BUTTON_Y_WIDTH 37


//#define CONTACT4_SCREEN_CODE    0000000000001101
#define CONTACT4_BUTTON_X 0
#define CONTACT4_BUTTON_Y 201
#define CONTACT4_BUTTON_X_WIDTH 260
#define CONTACT4_BUTTON_Y_WIDTH 37
/****************************/



//// LOGS SCREEN DEFINES ////
/* Can center the main button, but have to change variable name. Already defined in CONTACTS DEFINES.
   
    #define MAIN_BUTTON_X
    #define MAIN_BUTTON_Y
    #define MAIN_BUTTON_X_WIDTH
    #define MAIN_BUTTON_Y_WIDTH

*/

// 40 x 80 pixels
#define LOG_PG_DOWN_BUTTON_X    280
#define LOG_PG_DOWN_BUTTON_Y    100
#define LOG_PG_DOWN_BUTTON_X_WIDTH  40
#define LOG_PG_DOWN_BUTTON_Y_WIDTH  80
 
#define LOG_PG_UP_BUTTON_X  280 
#define LOG_PG_UP_BUTTON_Y  90
#define LOG_PG_UP_BUTTON_X_WIDTH 40
#define LOG_PG_UP_BUTTON_Y_WIDTH 80

/****************************/

//// COMPOSE SCREEN BUTTONS DEFINES ////
/* Can center the main button, but have to change variable name. Already defined in CONTACTS DEFINES.
   
    #define MAIN_BUTTON_X
    #define MAIN_BUTTON_Y
    #define MAIN_BUTTON_X_WIDTH
    #define MAIN_BUTTON_Y_WIDTH

*/

// Bottom right, 40 x 80 pixels
#define SEND_BUTTON_X   280
#define SEND_BUTTON_Y   160
#define SEND_BUTTON_X_WIDTH 40
#define SEND_BUTTON_Y_WIDTH 80

/****************************/

//// RECEIVED SCREEN DEFINES ////

#define COMPOSE_BUTTON_X    240
#define COMPOSE_BUTTON_Y    0
#define COMPOSE_BUTTON_X_WIDTH  80
#define COMPOSE_BUTTON_Y_WIDTH  80

/****************************/
